### ISSUE TITLE
Stuck on "Active synchronization" block 563600

### ISSUE THREAD

**Issue by abysoltech** [ergoplatform/ergodocs#3]
Fresh install on Raspberry Pi 4 Ubuntu 21.10 impish 4 vcpu 8 GB ram
250 GB /dev/sda2 fast usb drive
as per troubleshooting steps, I see no errors, exceptions, only warnings about version mismatch (i'm on latest 4.0.23).
It was moving relatively fast (2 days) to this block height 563600 and then it "stuck". Tried to restart it, give it more 6GB of ram or less 3GB to the Xmx, reverted back to recommended 4GB after restart and reboot.
Nothing glaring that I can see, some logs...
`01:51:21.019 INFO  [tor.default-dispatcher-13] o.e.n.ErgoNodeViewSynchronizer - Processing 400 non-tx invs (of type 101) from ConnectedPeer(connection: ConnectionId(remote=/54.37.236.119:9030, local=/10.10.10.70:45754, direction=Outgoing) , remote version: Some(4.0.10))
01:51:22.102 DEBUG [tor.default-dispatcher-14] s.c.n.PeerConnectionHandler - Received message MessageSpec(65: Sync) from ConnectionId(remote=/46.101.82.98:9030, local=/10.10.10.70:47706, direction=Outgoing)
01:51:22.104 DEBUG [tor.default-dispatcher-14] o.e.n.ErgoNodeViewSynchronizer - Processing sync from ConnectedPeer(connection: ConnectionId(remote=/46.101.82.98:9030, local=/10.10.10.70:47706, direction=Outgoing) , remote version: Some(4.0.23))
01:51:22.107 DEBUG [tor.default-dispatcher-14] o.e.n.ErgoNodeViewSynchronizer - Comparison with ConnectedPeer(connection: ConnectionId(remote=/46.101.82.98:9030, local=/10.10.10.70:47706, direction=Outgoing) , remote version: Some(4.0.23)) having starting points Vector(Header({"extensionId":"800f5129fff7b41adf77285a3d6f3cfa483f7b0367f12e5910b012329ffe2d9a","difficulty":"1645371906326528","votes":"000000","timestamp":1645667278395,"size":220,"stateRoot":"8fc6d1b50fde4c5306fcdcdb34a322e19eb8c71e0365a9d197b75ce2321be5b318","height":692734,"nBits":117823605,"version":2,"id":"0369d8b6c6691ec871d1c20544c7898abccb6aacffd3071bd6ed1e25fe9d9c22","adProofsRoot":"467bed64e8dd9b40d328fae6a91dd3e53286915084dc968fcd564e2c87d11ac7","transactionsRoot":"7261da2861291fb746a89a67fc4b1cda17903bd4448b9b3ed547fc4f07ca2285","extensionHash":"e2a0335d8059c4bee2da1d8b2ed21c9d55d46a82a815184ed1c623645aea9565","powSolutions":{"pk":"02ebaaeb381c9d855af1807781fa20ef6c0c34833275ce7913a9e4469f7bcb3bec","w":"0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798","n":"056f8600a113ab96","d":0},"adProofsId":"0ecc1ec0c602b8309c43dfbfe25b7e55c7db0fc19994152fb222b10a66bd17bf","transactionsId":"4de026313880f1ada4dd8bed33aad71ab26200b43f3f44b416251bf326627fa4","parentId":"8f05ef7ce7557c50d8cfbe5de724886d3152d390cd2470ac82a086eba002f558"}), Header({"extensionId":"243e2791f812b6951dcd47628f75fa1491119f5509d9366ed557843813cd4e11","difficulty":"1645371906326528","votes":"000000","timestamp":1645664963209,"size":220,"stateRoot":"8cc3b61ddb0d09ca4d35a0928f802b808167c1bb3ea1dc2807b651e7ad7b069e18","height":692718,"nBits":117823605,"version":2,"id":"1d01f84e430a43b4ae2b7c10c2173e4c5b05f175e9393a37afc1bdaf79e0e147","adProofsRoot":"c02bb84064800940a0cc677b466adcebf2ef1bc6141fc5b468df5dc10fc3ee38","transactionsRoot":"32faa37fdab1517359dae786eee26619221bb49dc21748cf9606cdc3c0263983","extensionHash":"89a1fe16e7bcc10192d1770c7862bfcc8bea838d5fd72cadce9867782f5ee326","powSolutions":{"pk":"02a1f56716cb8df4feb9371437904b9125b82db939238cd7d948786db33de3139f","w":"0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798","n":"189e0005367ed834","d":0},"adProofsId":"738d1db600565dfd8b4b50d02b872c655e61399bd0288efcba127b2180e73a10","transactionsId":"a6884a000c53168baf648b2508ab3bbb274de1ca78505002c82e44c81f41a82a","parentId":"284b0c4937f84b98eb1c9be3f6df6ebb695ac422d015462f4829a7fc6bd902a1"}), Header({"extensionId":"ed663b4e142695c760b86c6e74440a65e56240f4848e7e87b1e50b58be702b0b","difficulty":"1645371906326528","votes":"000000","timestamp":1645653066455,"size":220,"stateRoot":"558109b7434e936904c17b4e6429f4d790a34efca55c0a756991d14d5e19a73d18","height":692606,"nBits":117823605,"version":2,"id":"a61044d92cc73120163f3c6925db16e3db3bc805b3e3f773cbaadb5e11070bf9","adProofsRoot":"b0693829cccc960a78ddc49e789306551a1e0fd670502152c8602b97bf9b8c46","transactionsRoot":"a940af149b07a8b909a1d1ecf7e2b798abfdacd4a842407fd82924dc22718441","extensionHash":"4f31c7d67cd1cf69d9f2a3c035e3ac0b5e99a4290c6650f8008b4989a9cec84b","powSolutions":{"pk":"0274e729bb6615cbda94d9d176a2f1525068f12b330e38bbbf387232797dfd891f","w":"0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798","n":"179d000611071a6a","d":0},"adProofsId":"71617fae6b954a2f2a2a30f8c7bf46253c592245bda1e9aefdf36f96f0dfb4f9","transactionsId":"8083843503c35dc004cebffee73091da3e1de5be6fee7dc64290a84b505b7d3c","parentId":"7cb4bd56f0240580b0a7c150b17628ce7bdb9f5ac83fce67e3f092fb723fbacd"}), Header({"extensionId":"d51cec39536f958ba51c6cc388b6b7024045f5d58ead83cb1951afecca25b5ee","difficulty":"1649383405780992","votes":"040000","timestamp":1645607316863,"size":220,"stateRoot":"f8d6e3e85b92ba14071ea6dcf1e41bd711c89d928a7a4fb111aaf98ff7716ff518","height":692222,"nBits":117824539,"version":2,"id":"15274abcbbf454259629745865385b39fd69fda48a4c093c7257ec4aa97bf864","adProofsRoot":"af4b87c732f1c159d53925955a5e507450e1f71cf60b9f486c1b8fead8c856a3","transactionsRoot":"2638b604cf4a7b7dc0062b830666b0749c18f9565c107f2c516cebca812b1b19","extensionHash":"98e64704c0cf27ca641d66c2530edb85bab2db34b1f2e2915b70f39d4ec19e6a","powSolutions":{"pk":"02ebaaeb381c9d855af1807781fa20ef6c0c34833275ce7913a9e4469f7bcb3bec","w":"0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798","n":"040267028e0f9174","d":0},"adProofsId":"c16e8f817bb64635418784500106ef90700073ad87e27b1268ef7e6c5c90a2bc","transactionsId":"eb0d71f52e7a3501cd6768338eb901318cc37e9e63ed261f967ab0edb5b7f43c","parentId":"da36b5d63cf5e38ad6e020d06b73914064cd60da908fcc16ce203b1f95d52fba"})). Comparison result is Older.
01:51:22.107 DEBUG [tor.default-dispatcher-14] o.e.n.ErgoNodeViewSynchronizer - Peer ConnectedPeer(connection: ConnectionId(remote=/46.101.82.98:9030, local=/10.10.10.70:47706, direction=Outgoing) , remote version: Some(4.0.23)) is older, its height Some(692734)
01:51:22.108 INFO  [tor.default-dispatcher-14] s.c.n.PeerConnectionHandler - Send message MessageSpec(65: Sync) to ConnectionId(remote=/46.101.82.98:9030, local=/10.10.10.70:47706, direction=Outgoing)`

Seems working but ot show no progress beyond the block in question.....
Running out of ideas. Any suggestions? Need more info, let me know please.
Thanks
Mark

**Comment by glasgowm148** [comment]
Sorry I missed this (Github notifications suck) - but the node repo is [here](https://github.com/ergoplatform/ergo/issues)

Join one of the support chats if you're still experiencing issues. 

https://linktr.ee/ergoplatform
