### ISSUE TITLE
Idea for another job 

### ISSUE THREAD

**Issue by wombo22** [ergoplatform/ergodocs#49]
create a glossary page for ergo ecosystem like what is in spectrum docs: https://docs.spectrum.fi/concepts/glossary

**Comment by wombo22** [comment]
https://docs.google.com/document/d/1BEDdVsB04-WHjuQqyvdw6k49FU7eEnhF6OEHXXs3Wh0/edit

**Comment by glasgowm148** [comment]
Thanks for the contribution!

https://docs.ergoplatform.com/glossary/

Now to fix up all the URLs)
