### ISSUE TITLE
Transfer over any remaining information from ergonaut.space 

### ISSUE THREAD

**Issue by wombo22** [ergoplatform/ergodocs#50]
"At a quick skim I think most of it is over now, probably just going through it and seeing if anything there would be more suited on the docs, or even linked from the docs."

Went through it and made a list of items that can possibly (not at all required) be added/linked: https://docs.google.com/document/d/19PA1IOe0_UOms6zH1X7Wm3yjIIubtbbRTUsvcDMkKUU/edit?usp=sharing 

 Seems mainly just updating a few pages for dApps.

**Comment by glasgowm148** [comment]
Thanks for the overview - amendments pushed!
